name: exploring
on: 
    push:
jobs:
    docker-login:
            runs-on: ubuntu-latest
            steps:
              - name: Login to Docker Hub
                uses: docker/login-action@v3.3.0
                with: 
                    username: ${{ vars.DOCKER_USERNAME }} 
                    password: ${{ secrets.DOCKER_PASSWORD }}
